(function () {
  var list = [];
  function m(row) {
    var d = {
      wifi: "works",
      audio: "works",
      webcam: "works",
      fingerprint: "unknown",
      gpu: "works",
      suspend: "works",
      type: "laptop",
      tags: ""
    };
    for (var k in row) d[k] = row[k];
    list.push(d);
  }

  /* Dell — official Panther/Wildcat plus community revivals */
  m({ id: "dell-xps-14-2026", brand: "Dell", name: "Dell XPS 14 (2026, Panther Lake)", rating: "gold", href: "dell-xps-14-2026.html", fingerprint: "works", tags: "xps panther oled 358H", summary: "Official day-one collab. Wi-Fi 7, haptic trackpad, IPU7 camera, speaker tunings. DHH’s current favorite laptop." });
  m({ id: "dell-xps-16-2026", brand: "Dell", name: "Dell XPS 16 (2026, Panther Lake)", rating: "gold", href: "dell-xps-14-2026.html", fingerprint: "works", tags: "xps panther oled", summary: "Same linux-ptl enablement as the 14. Idle around 2.2 W reported on the OLED 16 with Vantablack." });
  m({ id: "dell-xps-13-2026", brand: "Dell", name: "Dell XPS 13 (2026, Wildcat Lake)", rating: "gold", href: "dell.html#dell-xps-13-2026", fingerprint: "works", tags: "xps wildcat DX13260 sidecar", summary: "DHH’s value pick vs MacBook Neo. 120 Hz matte, ~$699 US. Sidecar-amp quirk package for SKU 0E53." });
  m({ id: "dell-xps-13-9370", brand: "Dell", name: "Dell XPS 13 9370 (2018)", rating: "silver", href: "dell.html#dell-xps-13-9370", tags: "xps 9370", summary: "Community daily driver next to Beelink minis. Old but installs cleanly." });
  m({ id: "dell-xps-7590", brand: "Dell", name: "Dell XPS 15 7590", rating: "bronze", href: "dell.html#dell-xps-7590", fingerprint: "fails", tags: "xps 7590 goodix", summary: "Installs. Goodix fingerprint is detected and still cannot enroll — libfprint, not Omarchy-specific." });
  m({ id: "dell-latitude-vintage", brand: "Dell", name: "Dell Latitude (vintage, ~2013)", rating: "silver", href: "dell.html#dell-latitude-vintage", webcam: "unknown", fingerprint: "unknown", tags: "latitude revival", summary: "Hub setup: 13-year-old Latitude revived. Expect Intel Wi-Fi and no fingerprint drama." });
  m({ id: "dell-inspiron-vintage", brand: "Dell", name: "Dell Inspiron (vintage laptop)", rating: "silver", href: "dell.html#dell-inspiron-vintage", webcam: "unknown", fingerprint: "unknown", tags: "inspiron revival", summary: "Community revival photo. Fine as a potato if the disk is healthy." });
  m({ id: "dell-alienware-x17-r1", brand: "Dell", name: "Alienware x17 R1", rating: "silver", href: "nvidia-laptops.html#dell-alienware-x17-r1", type: "laptop", fingerprint: "unknown", gpu: "workaround", tags: "alienware nvidia gaming", summary: "Hub gaming-laptop setup with dual externals. NVIDIA hybrid rules apply." });
  m({ id: "dell-alienware-generic", brand: "Dell", name: "Alienware gaming laptop (other)", rating: "bronze", href: "nvidia-laptops.html", gpu: "workaround", tags: "alienware nvidia", summary: "Tested in the wild. Treat like any muxed NVIDIA box: nomodeset if the ISO blacks out." });

  /* Framework */
  m({ id: "framework-13-pro-ptl", brand: "Framework", name: "Framework Laptop 13 Pro (Panther Lake)", rating: "gold", href: "framework.html#framework-13-pro-ptl", fingerprint: "works", tags: "framework 13 pro panther 2w", summary: "On DHH’s recommend list. ~2 W idle on IPS in Omarchy 3.6 notes. Repairable nerd laptop." });
  m({ id: "framework-13-amd", brand: "Framework", name: "Framework Laptop 13 (AMD Ryzen AI 9 HX 370)", rating: "silver", href: "framework.html#framework-13-amd", fingerprint: "works", tags: "framework 13 ryzen hx370", summary: "Many Hub photos. AMD audio input has a dedicated Omarchy fix script." });
  m({ id: "framework-13-intel", brand: "Framework", name: "Framework Laptop 13 (Intel 12th–13th gen)", rating: "silver", href: "framework.html#framework-13-intel", fingerprint: "works", tags: "framework 13 intel", summary: "Common daily driver. Expansion cards and batch BIOS matter more than Omarchy itself." });
  m({ id: "framework-12", brand: "Framework", name: "Framework Laptop 12 (Intel i5-1334U)", rating: "silver", href: "framework.html#framework-12", fingerprint: "works", tags: "framework 12 convertible", summary: "DHH posted a sub-$1000 unit. Also used as a travel companion to a Beelink SER9." });
  m({ id: "framework-16", brand: "Framework", name: "Framework Laptop 16", rating: "silver", href: "framework.html#framework-16", fingerprint: "works", gpu: "workaround", tags: "framework 16 qmk-hid dgpu", summary: "ISO ships qmk-hid for the input module. dGPU models follow NVIDIA/AMD laptop caveats." });
  m({ id: "framework-desktop", brand: "Framework", name: "Framework Desktop (Strix Halo / 395+)", rating: "silver", href: "framework.html#framework-desktop", type: "desktop", webcam: "n/a", fingerprint: "n/a", gpu: "workaround", tags: "framework desktop 395+ strix halo", summary: "DHH’s top desktop pick. Fast, quiet, 128 GB configs in the wild. Early Chromium/GPU crash threads exist." });
  m({ id: "framework-mattbook", brand: "Framework", name: "Mattbook UMPC (Framework 13 board)", rating: "experimental", href: "framework.html#framework-mattbook", type: "handheld", fingerprint: "n/a", tags: "framework umpc touch 10 inch", summary: "Community handheld: Framework 13 mainboard + 10.1\" touch. Not a SKU Framework sells." });

  /* Lenovo */
  m({ id: "thinkpad-x220", brand: "Lenovo", name: "ThinkPad X220 (2011)", rating: "gold", href: "thinkpad.html#thinkpad-x220", tags: "thinkpad x220 potato 2gb", summary: "Official potato demo: 2 GB RAM, still usable. Safest cheap ThinkPad." });
  m({ id: "thinkpad-t440s", brand: "Lenovo", name: "ThinkPad T440s", rating: "silver", href: "thinkpad.html#thinkpad-t440s", tags: "thinkpad t440s", summary: "Reddit: i5-4300U / 8 GB SATA, described as blazing. Check the disk before you blame the DE." });
  m({ id: "thinkpad-t480", brand: "Lenovo", name: "ThinkPad T480", rating: "silver", href: "thinkpad.html#thinkpad-t480", tags: "thinkpad t480", summary: "Classic revival. One report of 2 s app launches until the power profile is set to performance." });
  m({ id: "thinkpad-t14", brand: "Lenovo", name: "ThinkPad T14 (Intel/AMD, Gen 1–4)", rating: "silver", href: "thinkpad.html#thinkpad-t14", tags: "thinkpad t14 dual-boot", summary: "Usually excellent. Dual-boot: Limine may be the only extra firmware entry. Autologin after LUKS is intended." });
  m({ id: "thinkpad-x1c-g8", brand: "Lenovo", name: "ThinkPad X1 Carbon Gen 8", rating: "silver", href: "thinkpad.html#thinkpad-x1c-g8", fingerprint: "unknown", tags: "thinkpad x1 carbon gen8", summary: "Hub: used X1C Gen 8, install under 10 minutes. Also used as a dual-monitor battlestation." });
  m({ id: "thinkpad-x1c-other", brand: "Lenovo", name: "ThinkPad X1 Carbon (other gens)", rating: "silver", href: "thinkpad.html", fingerprint: "unknown", tags: "thinkpad x1 carbon", summary: "Same family as Gen 8. Newer gens with Goodix/Synaptics sensors vary on fingerprint." });
  m({ id: "thinkpad-yoga-370", brand: "Lenovo", name: "ThinkPad Yoga 370", rating: "silver", href: "thinkpad.html#thinkpad-yoga-370", type: "2-in-1", tags: "thinkpad yoga 370 convertible", summary: "7th-gen i7 convertible. Owner compared it favorably to an M3 Max for everyday speed." });
  m({ id: "thinkpad-e14-g7", brand: "Lenovo", name: "ThinkPad E14 Gen 7", rating: "bronze", href: "thinkpad.html#thinkpad-e14-g7", audio: "workaround", webcam: "workaround", tags: "thinkpad e14 gen7", summary: "3.7 update reports of broken sound/mic/camera. Snapshot rollback, then file an issue." });
  m({ id: "lenovo-yoga-generic", brand: "Lenovo", name: "Lenovo Yoga (Intel/AMD, not Snapdragon)", rating: "silver", href: "thinkpad.html#lenovo-yoga-generic", type: "2-in-1", tags: "yoga convertible", summary: "Hub install from WSL-to-native. Convertible tablet mode is a Hyprland extra, not a promise." });
  m({ id: "lenovo-legion", brand: "Lenovo", name: "Lenovo Legion (gaming, NVIDIA)", rating: "silver", href: "nvidia-laptops.html#lenovo-legion", gpu: "workaround", tags: "legion nvidia gaming", summary: "Hub dual-monitor Legion setup. Hybrid GPU / battery same story as ROG." });
  m({ id: "lenovo-ideapad-slim-3x", brand: "Lenovo", name: "Lenovo IdeaPad Slim 3x (Snapdragon X)", rating: "experimental", href: "apple-silicon.html#snapdragon-x", wifi: "workaround", audio: "workaround", gpu: "workaround", tags: "ideapad snapdragon x arm", summary: "r/omarchy: no public x86 ISO path. aarch64 PRs exist; do not expect a 90-second install." });

  /* Apple Intel */
  m({ id: "macbook-white-2007", brand: "Apple", name: "MacBook White (Late 2007)", rating: "bronze", href: "macbook-intel.html#macbook-white-2007", wifi: "workaround", audio: "unknown", webcam: "unknown", fingerprint: "n/a", gpu: "workaround", suspend: "unknown", tags: "macbook 2007 vintage", summary: "Hub revival on 3.0.1 with Docker and a local LLM. Expect Broadcom Wi-Fi and patience." });
  m({ id: "mbp-2009", brand: "Apple", name: "MacBook Pro 13-inch (Mid-2009)", rating: "silver", href: "macbook-intel.html#mbp-2009", fingerprint: "n/a", tags: "macbook pro 2009 vintage", summary: "Hub: revived with Omarchy 3.0.1. Official potato energy." });
  m({ id: "mbp-2012", brand: "Apple", name: "MacBook Pro 13-inch (2012, i5-3210M)", rating: "silver", href: "macbook-intel.html#mbp-2012", fingerprint: "n/a", tags: "macbook pro 2012", summary: "Multiple revival posts (v3.0.2). Replace the HDD if it still has one." });
  m({ id: "macbook-air-2012", brand: "Apple", name: "MacBook Air (2012–2015)", rating: "silver", href: "macbook-intel.html#macbook-air-2012", fingerprint: "n/a", tags: "macbook air vintage", summary: "Community four-minute install reports. Broadcom Wi-Fi is auto-fixed on Apple hardware." });
  m({ id: "macbook-12", brand: "Apple", name: "MacBook 12-inch (Retina, 2015–2017)", rating: "silver", href: "macbook-intel.html#macbook-12", fingerprint: "n/a", tags: "macbook 12 retina butterfly", summary: "Hub ultra-portable setup. Keyboard is the hardware risk, not Omarchy." });
  m({ id: "mbp-2015", brand: "Apple", name: "MacBook Pro 13-inch (Early 2015)", rating: "silver", href: "macbook-intel.html#mbp-2015", fingerprint: "n/a", tags: "macbook pro 2015", summary: "Lab and music-studio Hub photos. i5-5257U / 8 GB confirmed on 3.2.3." });
  m({ id: "mbp-t1", brand: "Apple", name: "MacBook Pro Touch Bar (T1, 2016–2017)", rating: "bronze", href: "macbook-intel.html#mbp-t1", wifi: "workaround", audio: "fails", webcam: "fails", fingerprint: "fails", tags: "macbook t1 touch bar a1706 a1707", summary: "Installs. Full-disk wipe bricks Touch Bar, webcam, audio until macOS rewrites T1 firmware. Dual-boot or don’t." });
  m({ id: "mbp-t2", brand: "Apple", name: "MacBook Pro (T2, 2018–2020)", rating: "silver", href: "macbook-intel.html#mbp-t2", webcam: "workaround", fingerprint: "fails", suspend: "workaround", tags: "macbook t2 2018 2019 2020", summary: "Supported. linux-t2 auto-applied. Suspend wants s2idle. Keep the Apple EFI blob." });
  m({ id: "mba-t2", brand: "Apple", name: "MacBook Air Retina (T2, 2018–2020)", rating: "silver", href: "macbook-intel.html#mba-t2", webcam: "workaround", fingerprint: "fails", suspend: "workaround", tags: "macbook air t2", summary: "Same T2 stack as the Pro. Official Mac chapter lists these model years." });
  m({ id: "mac-mini-2012", brand: "Apple", name: "Mac mini (Early 2012)", rating: "silver", href: "macbook-intel.html#mac-mini-2012", type: "desktop", webcam: "n/a", fingerprint: "n/a", tags: "mac mini 2012", summary: "Community: ~19 minute install, cooler than last macOS. Pair with any display." });
  m({ id: "mac-mini-2018", brand: "Apple", name: "Mac mini (2018, T2)", rating: "silver", href: "macbook-intel.html#mac-mini-2018", type: "desktop", webcam: "n/a", fingerprint: "n/a", suspend: "workaround", tags: "mac mini 2018 t2", summary: "T2 mini. Good Mac-replacement desk if you keep firmware intact." });
  m({ id: "imac-2012", brand: "Apple", name: "iMac (Late 2012)", rating: "silver", href: "macbook-intel.html#imac-2012", type: "desktop", fingerprint: "n/a", tags: "imac 2012 fusion drive", summary: "Several resurrections after Fusion Drive death. Swap to SSD." });
  m({ id: "imac-2017-21", brand: "Apple", name: "iMac 21.5-inch (2017, i5 / 8 GB)", rating: "silver", href: "macbook-intel.html#imac-2017-21", type: "desktop", fingerprint: "n/a", tags: "imac 2017 21", summary: "Hub: six-minute install, Tokyo Night. Soldered RAM is the limiter." });
  m({ id: "imac-2017-27", brand: "Apple", name: "iMac 27-inch 5K (2017)", rating: "silver", href: "macbook-intel.html#imac-2017-27", type: "desktop", fingerprint: "n/a", gpu: "workaround", tags: "imac 2017 5k 5120", summary: "Community native 5120×2880 reports plus extra GPU/HiDPI work. Speakers/mic/EarPods called out as working on one write-up." });
  m({ id: "imac-2018-5k", brand: "Apple", name: "iMac Retina 5K (2018)", rating: "silver", href: "macbook-intel.html#imac-2018-5k", type: "desktop", fingerprint: "n/a", tags: "imac 2018 5k t2", summary: "Used as an AI engineering desk, SSH to a bigger build box." });
  m({ id: "mac-pro-2013", brand: "Apple", name: "Mac Pro (Late 2013, cylinder)", rating: "silver", href: "macbook-intel.html#mac-pro-2013", type: "desktop", webcam: "n/a", fingerprint: "n/a", gpu: "workaround", tags: "mac pro trash can 2013", summary: "Hub install-screen photo. Dual-GPU / display-port routing is the homework." });

  /* Apple Silicon / ARM */
  m({ id: "mba-m1", brand: "Apple", name: "MacBook Air M1", rating: "experimental", href: "apple-silicon.html#mba-m1", wifi: "workaround", audio: "workaround", webcam: "workaround", fingerprint: "workaround", gpu: "workaround", suspend: "unknown", tags: "m1 air apple silicon omarchy-m", summary: "Omarchy M team is targeting M1/M2. Community Omarchy Mac exists. Not the public x86 ISO." });
  m({ id: "mbp-m1", brand: "Apple", name: "MacBook Pro M1 / M1 Pro / M1 Max", rating: "experimental", href: "apple-silicon.html#mbp-m1", wifi: "workaround", audio: "workaround", webcam: "workaround", fingerprint: "workaround", gpu: "workaround", tags: "m1 pro max apple silicon", summary: "Same Omarchy M / omarchy-mac path as the Air. Try Omarchy VM is the supported taste-test." });
  m({ id: "mba-m2", brand: "Apple", name: "MacBook Air M2", rating: "experimental", href: "apple-silicon.html#mba-m2", wifi: "workaround", audio: "workaround", webcam: "workaround", fingerprint: "workaround", gpu: "workaround", tags: "m2 air usb-c display", summary: "Community: external displays over USB-C enabled. Still not a one-stick official ISO." });
  m({ id: "mbp-m2", brand: "Apple", name: "MacBook Pro M2 / M2 Pro / M2 Max", rating: "experimental", href: "apple-silicon.html#mbp-m2", wifi: "workaround", audio: "workaround", webcam: "workaround", fingerprint: "workaround", gpu: "workaround", tags: "m2 pro max", summary: "Hub “Omarchy Mac” desktop photo. Official M-series native install is still in progress." });
  m({ id: "mba-m3", brand: "Apple", name: "MacBook Air M3", rating: "experimental", href: "apple-silicon.html#mba-m3", wifi: "unknown", audio: "unknown", webcam: "unknown", fingerprint: "unknown", gpu: "workaround", tags: "m3 air display controller", summary: "Omarchy M note: M3 Air internal display via Apple’s hardware display controller went from unusable to usable. Early." });
  m({ id: "apple-m4", brand: "Apple", name: "M4 Macs", rating: "broken", href: "apple-silicon.html#apple-m4", wifi: "n/a", audio: "n/a", webcam: "n/a", fingerprint: "n/a", gpu: "n/a", suspend: "n/a", tags: "m4 apple silicon", summary: "First Omarchy M release target is M1/M2. Do not wipe an M4 expecting the 4.0.3 ISO to boot." });
  m({ id: "yoga-slim-7x", brand: "Lenovo", name: "Lenovo Yoga Slim 7x (Snapdragon X)", rating: "experimental", href: "apple-silicon.html#yoga-slim-7x", type: "laptop", wifi: "workaround", audio: "workaround", gpu: "workaround", tags: "yoga slim 7x snapdragon x1e", summary: "PR #8672 live-session: Limine, Wi-Fi, BT, speakers, mic on one unit. Not the public ISO." });
  m({ id: "hp-elitebook-ultra-g1q", brand: "HP", name: "HP EliteBook Ultra G1q (Snapdragon X)", rating: "experimental", href: "apple-silicon.html#hp-elitebook-ultra-g1q", wifi: "workaround", audio: "unknown", gpu: "workaround", tags: "elitebook snapdragon x1e-78-100", summary: "PR testing: installs, native display, Wi-Fi, BT, keyboard, touchpad, touchscreen on linux-aarch64 7.2." });
  m({ id: "asus-vivobook-s15-x", brand: "ASUS", name: "ASUS Vivobook S15 (Snapdragon X)", rating: "experimental", href: "apple-silicon.html#asus-vivobook-s15-x", wifi: "workaround", audio: "unknown", gpu: "unknown", tags: "vivobook snapdragon", summary: "Reached installer welcome + Wi-Fi in a live session. Not a confirmed daily driver." });

  /* ASUS */
  m({ id: "asus-expertbook-ptl", brand: "ASUS", name: "ASUS ExpertBook (Panther Lake)", rating: "gold", href: "asus.html#asus-expertbook-ptl", fingerprint: "works", tags: "expertbook panther b9406", summary: "3.7: boot, screen, touchpad, fingerprint. Tree also has B9406 display/touchpad/backlight fixes." });
  m({ id: "asus-zenbook-s16", brand: "ASUS", name: "ASUS Zenbook S16", rating: "silver", href: "asus.html#asus-zenbook-s16", tags: "zenbook s16 oled", summary: "Hub install photo. Reddit: OLED Zenbook 14 with Intel 258V also reported working, clicky pad aside." });
  m({ id: "asus-zenbook-14-258v", brand: "ASUS", name: "ASUS Zenbook 14 (Intel Core Ultra 258V)", rating: "silver", href: "asus.html#asus-zenbook-14-258v", fingerprint: "unknown", tags: "zenbook 14 lunar lake 258v", summary: "r/omarchy: out of box, OLED, 32 GB. Touchpad click worse than a Mac, otherwise a workhorse." });
  m({ id: "asus-zenbook-duo", brand: "ASUS", name: "ASUS Zenbook Duo", rating: "silver", href: "asus.html#asus-zenbook-duo", type: "2-in-1", tags: "zenbook duo dual-screen", summary: "Hub dual-screen laptop. Second panel is extra Hyprland monitor work." });
  m({ id: "asus-flow-z13-2025", brand: "ASUS", name: "ASUS ROG Flow Z13 (2025, Strix Halo)", rating: "silver", href: "asus.html#asus-flow-z13-2025", type: "2-in-1", fingerprint: "unknown", tags: "flow z13 strix halo tablet", summary: "Hub “Omarchablet” on 128 GB. Community post-install script adds Cachy/g14 kernel, asusctl, TDP. Touchpad fix lives in Omarchy." });
  m({ id: "asus-g14-2023", brand: "ASUS", name: "ASUS ROG Zephyrus G14 (2023)", rating: "silver", href: "nvidia-laptops.html#asus-g14-2023", gpu: "workaround", suspend: "workaround", tags: "zephyrus g14 2023 4050", summary: "Reddit: 2023 G16/G14 4050 runs well. Kill the dGPU for battery." });
  m({ id: "asus-g14-2024", brand: "ASUS", name: "ASUS ROG Zephyrus G14 (2024, GA403, 4060)", rating: "silver", href: "nvidia-laptops.html#asus-g14-2024", gpu: "workaround", suspend: "workaround", tags: "zephyrus g14 2024 ga403uv 8945hs 4060", summary: "Long write-up: dual kernel to mux the 4060, asusctl, envycontrol. Installs; battery is the project." });
  m({ id: "asus-g16", brand: "ASUS", name: "ASUS ROG Zephyrus G16 (2023–2024, 4060/4070)", rating: "bronze", href: "nvidia-laptops.html#asus-g16", gpu: "workaround", tags: "zephyrus g16 4060 4070 black screen", summary: "Installs, then some units black-screen in Hyprland. nomodeset / NVIDIA env overrides." });
  m({ id: "asus-strix-g18", brand: "ASUS", name: "ASUS ROG Strix G18", rating: "silver", href: "nvidia-laptops.html#asus-strix-g18", gpu: "workaround", tags: "strix g18 nvidia", summary: "Reddit: stock install, no issues reported by that owner." });
  m({ id: "asus-tuf-f15", brand: "ASUS", name: "ASUS TUF F15", rating: "silver", href: "nvidia-laptops.html#asus-tuf-f15", gpu: "workaround", tags: "tuf f15 student", summary: "Hub student hostel setup with a Legion monitor. NVIDIA laptop caveats." });

  /* Mini PCs */
  m({ id: "beelink-eq-wildcat", brand: "Beelink", name: "Beelink EQ mini Wildcat", rating: "gold", href: "minipc.html#beelink-eq-wildcat", type: "mini-pc", webcam: "n/a", fingerprint: "n/a", tags: "beelink eq wildcat under 500", summary: "On DHH’s current mini-PC list: under $500, 12 GB + 512 GB NVMe." });
  m({ id: "beelink-ser8", brand: "Beelink", name: "Beelink SER8 (Ryzen 7 8745HS)", rating: "gold", href: "minipc.html#beelink-ser8", type: "mini-pc", webcam: "n/a", fingerprint: "n/a", tags: "beelink ser8 8745hs", summary: "The $499 Mac-replacement of 2025. DHH set one up in NYC in <15 min. Early Wi-Fi range complaints got a firmware fix." });
  m({ id: "beelink-ser9", brand: "Beelink", name: "Beelink SER9 / SER9 Pro (HX370 / H255)", rating: "gold", href: "minipc.html#beelink-ser9", type: "mini-pc", webcam: "n/a", fingerprint: "n/a", tags: "beelink ser9 hx370 h255", summary: "Very common next to Framework 13s. AMD iGPU, fast NVMe, few driver threads." });
  m({ id: "beelink-ser10", brand: "Beelink", name: "Beelink SER10 (HX470)", rating: "gold", href: "minipc.html#beelink-ser10", type: "mini-pc", webcam: "n/a", fingerprint: "n/a", tags: "beelink ser10 hx470", summary: "On DHH’s list: HX470 is “more than enough for almost anyone.”" });
  m({ id: "beelink-gtr9-pro", brand: "Beelink", name: "Beelink GTR9 Pro (Ryzen AI Max 395+)", rating: "gold", href: "minipc.html#beelink-gtr9-pro", type: "mini-pc", webcam: "n/a", fingerprint: "n/a", tags: "beelink gtr9 395+ 128gb", summary: "DHH: 128 GB unified, dead quiet under load. Same 395+ as Framework Desktop." });
  m({ id: "minisforum-um760", brand: "Minisforum", name: "Minisforum UM760", rating: "silver", href: "minipc.html#minisforum-um760", type: "mini-pc", webcam: "n/a", fingerprint: "n/a", tags: "minisforum um760", summary: "Hub desk with a Samsung monitor. AMD mini PC, should behave like a SER8." });
  m({ id: "intel-nuc", brand: "Intel", name: "Intel NUC", rating: "silver", href: "minipc.html#intel-nuc", type: "mini-pc", webcam: "n/a", fingerprint: "n/a", tags: "nuc mini-pc", summary: "Hub 24/7 office box. Broadwell-to-Raptor NUCs vary; avoid the oldest Celeron SKUs if you want a browser." });
  m({ id: "zima-board", brand: "Other", name: "Zima Board", rating: "experimental", href: "minipc.html#zima-board", type: "mini-pc", wifi: "unknown", audio: "unknown", webcam: "n/a", fingerprint: "n/a", gpu: "workaround", tags: "zima board sbc", summary: "Hub “janky found hardware.” SBC, not a laptop. Fun, not a daily driver target." });
  m({ id: "ryzen-mini-generic", brand: "Other", name: "Generic Ryzen mini PC (sub-$450)", rating: "silver", href: "minipc.html#ryzen-mini-generic", type: "mini-pc", webcam: "n/a", fingerprint: "n/a", tags: "ryzen mini 4k hyprland", summary: "Community: buttery 4K@60 Hyprland on a cheap Ryzen 7 box. Prefer AMD iGPU over NVIDIA." });

  /* Tuxedo / Slimbook */
  m({ id: "slimbook-preinstall", brand: "Slimbook", name: "Slimbook (Omarchy preinstall)", rating: "gold", href: "tuxedo.html#slimbook-preinstall", fingerprint: "unknown", tags: "slimbook preinstall", summary: "Factory Omarchy. Keyboard backlight patched in-tree. Confirm the SKU with the vendor." });
  m({ id: "tuxedo-infinitebook-pro-14", brand: "Tuxedo", name: "Tuxedo InfiniteBook Pro 14", rating: "gold", href: "tuxedo.html#tuxedo-infinitebook-pro-14", fingerprint: "unknown", tags: "tuxedo infinitebook 80wh 3k", summary: "On DHH’s list: matte 3K, 80 Wh battery, dual NVMe, ethernet, 1.45 kg. US ANSI right-shift is tiny." });
  m({ id: "tuxedo-other", brand: "Tuxedo", name: "Other Tuxedo / Clevo Linux laptops", rating: "silver", href: "tuxedo.html#tuxedo-other", tags: "tuxedo clevo backlight", summary: "Omarchy ships tuxedo-drivers and a backlight fix. Tuxedo OS is a different distro." });

  /* HP / Surface / Acer */
  m({ id: "hp-stream", brand: "HP", name: "HP Stream (Celeron, 2 GB RAM)", rating: "silver", href: "hp-surface.html#hp-stream", fingerprint: "n/a", gpu: "works", tags: "hp stream celeron potato", summary: "Core team (Ryan Hughes) posted v3.0.2 running on a dual-core Celeron + 2 GB, even on a CRT." });
  m({ id: "hp-348-g3", brand: "HP", name: "HP 348 G3", rating: "silver", href: "hp-surface.html#hp-348-g3", tags: "hp 348 g3 dual-boot", summary: "Reddit dual-boot report. Limine vs Windows entries vary by firmware." });
  m({ id: "hp-old-laptop", brand: "HP", name: "Old HP laptop (generic)", rating: "silver", href: "hp-surface.html#hp-old-laptop", webcam: "unknown", fingerprint: "unknown", tags: "hp vintage", summary: "Hub install-screen photo. Fine if it’s x86_64 and the disk works." });
  m({ id: "surface-laptop", brand: "Microsoft", name: "Microsoft Surface Laptop", rating: "silver", href: "hp-surface.html#surface-laptop", type: "laptop", audio: "workaround", fingerprint: "unknown", tags: "surface marvell keyboard", summary: "ISO includes linux-firmware-marvell and a Surface keyboard fix. Type Cover / camera still hit-or-miss by generation." });
  m({ id: "surface-pro", brand: "Microsoft", name: "Microsoft Surface Pro (Intel)", rating: "bronze", href: "hp-surface.html#surface-pro", type: "2-in-1", audio: "workaround", webcam: "workaround", fingerprint: "unknown", suspend: "workaround", tags: "surface pro tablet", summary: "Same Surface scripts. Tablet/pen is extra. Avoid ARM Surfaces." });
  m({ id: "acer-swift-14", brand: "Acer", name: "Acer Swift 14 (FPC fingerprint 10a5:a305)", rating: "silver", href: "hp-surface.html#acer-swift-14", fingerprint: "workaround", tags: "acer swift 14 fpc fingerprint", summary: "Reddit: sensor listed as supported, enroll failed, agent-rewrote the driver. Fingerprint is the only flagged pain." });
  m({ id: "redmibook-pro-15-2023", brand: "Other", name: "RedmiBook Pro 15 (2023, Ryzen)", rating: "silver", href: "hp-surface.html#redmibook-pro-15-2023", fingerprint: "unknown", tags: "redmibook xiaomi ryzen", summary: "r/omarchy: “works perfectly.” AMD laptop without NVIDIA mux fights." });

  /* Handhelds / odd form factors */
  m({ id: "steam-deck", brand: "Valve", name: "Steam Deck (LCD / OLED)", rating: "experimental", href: "handheld.html#steam-deck", type: "handheld", fingerprint: "n/a", tags: "steam deck pizzarchy gamescope", summary: "Community Pizzarchy image exists (controller-only installer). Unofficial — do not grab random ISOs. Official Omarchy ISO is not a Deck image." });
  m({ id: "custom-395-desktop", brand: "Other", name: "Custom desktop (Ryzen AI Max+ 395)", rating: "silver", href: "minipc.html#custom-395-desktop", type: "desktop", webcam: "n/a", fingerprint: "n/a", tags: "395+ strix halo custom", summary: "typecraft’s checkerboard-case box. Same APU as Framework Desktop / GTR9 Pro." });
  m({ id: "sff-5090", brand: "Other", name: "SFF desktop (9800X3D + RTX 5090)", rating: "bronze", href: "nvidia-laptops.html#sff-5090", type: "desktop", webcam: "n/a", fingerprint: "n/a", gpu: "workaround", tags: "5090 9800x3d sff", summary: "Hub 9.95 L backpack box. 50-series installer black-screen issue applies." });
  m({ id: "nvidia-50-desktop", brand: "Other", name: "Desktop / laptop, RTX 50-series GPU", rating: "bronze", href: "nvidia-laptops.html#nvidia-50-desktop", type: "desktop", webcam: "n/a", fingerprint: "n/a", gpu: "workaround", tags: "rtx 5060 5070 5080 5090 nomodeset", summary: "Issue #7045: ISO hangs black without nomodeset. Hybrid VA-API can stutter until LIBVA is forced to the iGPU." });
  m({ id: "nvidia-40-desktop", brand: "Other", name: "Desktop, RTX 40-series (AMD/Intel CPU)", rating: "silver", href: "nvidia-laptops.html#nvidia-40-desktop", type: "desktop", webcam: "n/a", fingerprint: "n/a", gpu: "works", tags: "rtx 4070 4080 4090", summary: "Turing+ path uses nvidia-open-dkms. Desktops are easier than muxed laptops." });
  m({ id: "ipad-mini-utm", brand: "Apple", name: "iPad mini (UTM + JIT)", rating: "experimental", href: "apple-silicon.html#ipad-mini-utm", type: "handheld", wifi: "n/a", audio: "n/a", webcam: "n/a", fingerprint: "n/a", gpu: "n/a", suspend: "n/a", tags: "ipad utm jit vm", summary: "Hub: Omarchy in UTM with JIT. A VM on iPadOS, not a native port." });

  window.HARDWARE = list;
})();
